#!/usr/bin/env zsh

emulate -R zsh
setopt no_aliases no_multios pipe_fail

typeset submitted=''
integer read_status
[[ $1 == user_prompt_submit ]] || exit 1
IFS= read -r submitted
read_status=$?

case "$read_status:$submitted" in
  1:/help|1:/h)
    print -r -- $'999\t/new, /n\tStart a new session' >>"$SHELLFISH_STATE_DIR/help.tsv"
    exit 0
    ;;
  1:/new|1:/n)
    jq -cn --arg command "$SHELLFISH_EXECUTABLE" \
      '{action:"handoff",argv:[$command]}' >&3 || exit 1
    exit 11
    ;;
  *)
    exit 0
    ;;
esac
