#!/usr/bin/env zsh

emulate -R zsh
setopt no_aliases no_multios pipe_fail

typeset submitted=''
integer read_status
[[ $1 == user_prompt_submit ]] || exit 1
IFS= read -r submitted
read_status=$?

case "$read_status:$submitted" in
  1:/help|1:/h)
    print -r -- $'110\t/refresh, /r\tRerender current session; fix layout' >>"$SHELLFISH_TURN_STATE/help.tsv"
    exit 0
    ;;
  1:/refresh|1:/r)
    jq -cn --arg command "$SHELLFISH_EXECUTABLE" --arg path "$SHELLFISH_SESSION" \
      '{action:"handoff",argv:[$command,"--clear","--session",$path]}' >&3 || exit 1
    exit 11
    ;;
  *)
    exit 0
    ;;
esac
