#!/usr/bin/env zsh

emulate -R zsh
setopt no_aliases no_multios pipe_fail

typeset submitted='' header
integer read_status
IFS= read -r submitted
read_status=$?
case "$read_status:$submitted" in
  1:/help|1:/h) ;;
  *) exit 0 ;;
esac

IFS= read -r header <"$SHELLFISH_SESSION" || exit 1

{
  print -r -- $'shift+enter\tAdd a line instead of sending the message'
  print -r -- $'ctrl+c\tCancel an active request; otherwise exit'
  print -r -- $'↑, ↓\tNavigate prompt history'
  print -r -- $'/queue drop <N>\tDiscard queued prompt'
  print -r -- $'/queue clear\tDiscard all queued prompts'
  jq -r '.harness.user_prompt_submit[] |
    select(.help? != null) | [.help.usage, .help.description] | @tsv' \
    <<<"$header" || exit 1
  print -r -- $'/refresh, /r\tRerender current session; fix layout'
  print -r -- $'/quit, /q\tExit'
} | LC_ALL=C awk -F'\t' '
    function chars(text, copy) {
      copy=text
      gsub(/[\200-\277]/,"",copy)
      return length(copy)
    }
    { key[NR]=$1; desc[NR]=$2 }
    END {
      max=0
      for (i=1;i<=NR;i++) { l=chars(key[i]); if (l>max) max=l }
      for (i=1;i<=NR;i++) printf "%s%*s  %s\n", key[i], max-chars(key[i]), "", desc[i]
    }' >&2
exit 11
