#!/usr/bin/env zsh

emulate -R zsh
setopt extended_glob no_aliases no_multios pipe_fail

typeset submitted='' command
integer read_status command_status
IFS= read -r submitted
read_status=$?

case "$read_status:$submitted" in
  1:\!*) ;;
  *) exit 0 ;;
esac

command=${submitted#\!}
command=${command##[[:space:]]#}
if [[ -z $command ]]; then
  print -u2 -r -- 'usage: !COMMAND'
  exit 10
fi

print -r -- '$ '"$command"
unset SHELLFISH_SESSION SHELLFISH_TURN_STATE
unset SHELLFISH_MAX_CAPTURE_BYTES SHELLFISH_MODE SHELLFISH_MODEL SHELLFISH_TURN_ID SHELLFISH_VERBOSE
unset SHELLFISH_CONFIG_DIR
command zsh -f -c "$command" </dev/null 2>&1 3>&-
command_status=$?
(( ! command_status )) || print -r -- $'\n(exit '"$command_status"')'
jq -cn --arg prompt "$command" --argjson status "$command_status" \
  '{context:{prompt:$prompt,status:$status}}' >&3 || exit 1
exit 10
