#!/usr/bin/env zsh

emulate -R zsh
setopt no_aliases no_multios pipe_fail

typeset submitted=''
integer read_status
IFS= read -r submitted
read_status=$?

case "$read_status:$submitted" in
  1:/verbose|1:/v)
    if (( ${SHELLFISH_VERBOSE:-0} )); then
      jq -cn --arg command "$SHELLFISH_EXECUTABLE" --arg path "$SHELLFISH_SESSION" \
        '{action:"handoff",argv:[$command,"--clear","--session",$path]}' >&3 || exit 1
    else
      jq -cn --arg command "$SHELLFISH_EXECUTABLE" --arg path "$SHELLFISH_SESSION" \
        '{action:"handoff",argv:[$command,"--verbose","--clear","--session",$path]}' >&3 || exit 1
    fi
    exit 11
    ;;
  *)
    exit 0
    ;;
esac
