#!/usr/bin/env zsh

emulate -R zsh
setopt no_aliases no_multios pipe_fail

typeset submitted
IFS= read -r submitted
[[ "$?:$submitted" == 1:/new ]] || exit 0
jq -cn --arg executable "$SHELLFISH_EXECUTABLE" --arg session "$SHELLFISH_SESSION" \
  '{action:"handoff",argv:[$executable,"--session-from",$session]}' >&3
