#!/usr/bin/env zsh

emulate -R zsh
setopt no_aliases no_multios pipe_fail

typeset submitted=''
integer read_status
IFS= read -r submitted
read_status=$?

case "$read_status:$submitted" in
  1:/new)
    jq -cn --arg command "$SHELLFISH_EXECUTABLE" --arg source "$SHELLFISH_SESSION" \
      '{action:"handoff",argv:[$command,"--session-from",$source]}' >&3 || exit 1
    exit 11
    ;;
  *)
    exit 0
    ;;
esac
